# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ph4nt0m/Developer/playground

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ph4nt0m/Developer/playground/build/emscripten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.4.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ph4nt0m/Developer/playground/build/emscripten/CMakeFiles /Users/ph4nt0m/Developer/playground/build/emscripten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ph4nt0m/Developer/playground/build/emscripten/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyApp

# Build rule for target.
MyApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyApp
.PHONY : MyApp

# fast build rule for target.
MyApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/build
.PHONY : MyApp/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f vendor/spdlog/CMakeFiles/spdlog.dir/build.make vendor/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f vendor/assimp/CMakeFiles/uninstall.dir/build.make vendor/assimp/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f vendor/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build.make vendor/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f vendor/assimp/code/CMakeFiles/assimp.dir/build.make vendor/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) $(MAKESILENT) -f vendor/assimp/test/CMakeFiles/unit.dir/build.make vendor/assimp/test/CMakeFiles/unit.dir/build
.PHONY : unit/fast

src/Application.o: src/Application.cpp.o
.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Node.o: src/Node.cpp.o
.PHONY : src/Node.o

# target to build an object file
src/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Node.cpp.o
.PHONY : src/Node.cpp.o

src/Node.i: src/Node.cpp.i
.PHONY : src/Node.i

# target to preprocess a source file
src/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Node.cpp.i
.PHONY : src/Node.cpp.i

src/Node.s: src/Node.cpp.s
.PHONY : src/Node.s

# target to generate assembly for a file
src/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/Node.cpp.s
.PHONY : src/Node.cpp.s

src/core/Log.o: src/core/Log.cpp.o
.PHONY : src/core/Log.o

# target to build an object file
src/core/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/core/Log.cpp.o
.PHONY : src/core/Log.cpp.o

src/core/Log.i: src/core/Log.cpp.i
.PHONY : src/core/Log.i

# target to preprocess a source file
src/core/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/core/Log.cpp.i
.PHONY : src/core/Log.cpp.i

src/core/Log.s: src/core/Log.cpp.s
.PHONY : src/core/Log.s

# target to generate assembly for a file
src/core/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/core/Log.cpp.s
.PHONY : src/core/Log.cpp.s

src/core/Window.o: src/core/Window.cpp.o
.PHONY : src/core/Window.o

# target to build an object file
src/core/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/core/Window.cpp.o
.PHONY : src/core/Window.cpp.o

src/core/Window.i: src/core/Window.cpp.i
.PHONY : src/core/Window.i

# target to preprocess a source file
src/core/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/core/Window.cpp.i
.PHONY : src/core/Window.cpp.i

src/core/Window.s: src/core/Window.cpp.s
.PHONY : src/core/Window.s

# target to generate assembly for a file
src/core/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/core/Window.cpp.s
.PHONY : src/core/Window.cpp.s

src/io/cursor.o: src/io/cursor.cpp.o
.PHONY : src/io/cursor.o

# target to build an object file
src/io/cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/cursor.cpp.o
.PHONY : src/io/cursor.cpp.o

src/io/cursor.i: src/io/cursor.cpp.i
.PHONY : src/io/cursor.i

# target to preprocess a source file
src/io/cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/cursor.cpp.i
.PHONY : src/io/cursor.cpp.i

src/io/cursor.s: src/io/cursor.cpp.s
.PHONY : src/io/cursor.s

# target to generate assembly for a file
src/io/cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/cursor.cpp.s
.PHONY : src/io/cursor.cpp.s

src/io/filesystem.o: src/io/filesystem.cpp.o
.PHONY : src/io/filesystem.o

# target to build an object file
src/io/filesystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/filesystem.cpp.o
.PHONY : src/io/filesystem.cpp.o

src/io/filesystem.i: src/io/filesystem.cpp.i
.PHONY : src/io/filesystem.i

# target to preprocess a source file
src/io/filesystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/filesystem.cpp.i
.PHONY : src/io/filesystem.cpp.i

src/io/filesystem.s: src/io/filesystem.cpp.s
.PHONY : src/io/filesystem.s

# target to generate assembly for a file
src/io/filesystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/filesystem.cpp.s
.PHONY : src/io/filesystem.cpp.s

src/io/keyboard.o: src/io/keyboard.cpp.o
.PHONY : src/io/keyboard.o

# target to build an object file
src/io/keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/keyboard.cpp.o
.PHONY : src/io/keyboard.cpp.o

src/io/keyboard.i: src/io/keyboard.cpp.i
.PHONY : src/io/keyboard.i

# target to preprocess a source file
src/io/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/keyboard.cpp.i
.PHONY : src/io/keyboard.cpp.i

src/io/keyboard.s: src/io/keyboard.cpp.s
.PHONY : src/io/keyboard.s

# target to generate assembly for a file
src/io/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/io/keyboard.cpp.s
.PHONY : src/io/keyboard.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/platform/osx/OSXWindow.o: src/platform/osx/OSXWindow.cpp.o
.PHONY : src/platform/osx/OSXWindow.o

# target to build an object file
src/platform/osx/OSXWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/platform/osx/OSXWindow.cpp.o
.PHONY : src/platform/osx/OSXWindow.cpp.o

src/platform/osx/OSXWindow.i: src/platform/osx/OSXWindow.cpp.i
.PHONY : src/platform/osx/OSXWindow.i

# target to preprocess a source file
src/platform/osx/OSXWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/platform/osx/OSXWindow.cpp.i
.PHONY : src/platform/osx/OSXWindow.cpp.i

src/platform/osx/OSXWindow.s: src/platform/osx/OSXWindow.cpp.s
.PHONY : src/platform/osx/OSXWindow.s

# target to generate assembly for a file
src/platform/osx/OSXWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/platform/osx/OSXWindow.cpp.s
.PHONY : src/platform/osx/OSXWindow.cpp.s

src/platform/web/WebWindow.o: src/platform/web/WebWindow.cpp.o
.PHONY : src/platform/web/WebWindow.o

# target to build an object file
src/platform/web/WebWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/platform/web/WebWindow.cpp.o
.PHONY : src/platform/web/WebWindow.cpp.o

src/platform/web/WebWindow.i: src/platform/web/WebWindow.cpp.i
.PHONY : src/platform/web/WebWindow.i

# target to preprocess a source file
src/platform/web/WebWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/platform/web/WebWindow.cpp.i
.PHONY : src/platform/web/WebWindow.cpp.i

src/platform/web/WebWindow.s: src/platform/web/WebWindow.cpp.s
.PHONY : src/platform/web/WebWindow.s

# target to generate assembly for a file
src/platform/web/WebWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/platform/web/WebWindow.cpp.s
.PHONY : src/platform/web/WebWindow.cpp.s

src/render/PipelineManager.o: src/render/PipelineManager.cpp.o
.PHONY : src/render/PipelineManager.o

# target to build an object file
src/render/PipelineManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/PipelineManager.cpp.o
.PHONY : src/render/PipelineManager.cpp.o

src/render/PipelineManager.i: src/render/PipelineManager.cpp.i
.PHONY : src/render/PipelineManager.i

# target to preprocess a source file
src/render/PipelineManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/PipelineManager.cpp.i
.PHONY : src/render/PipelineManager.cpp.i

src/render/PipelineManager.s: src/render/PipelineManager.cpp.s
.PHONY : src/render/PipelineManager.s

# target to generate assembly for a file
src/render/PipelineManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/PipelineManager.cpp.s
.PHONY : src/render/PipelineManager.cpp.s

src/render/Render.o: src/render/Render.cpp.o
.PHONY : src/render/Render.o

# target to build an object file
src/render/Render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/Render.cpp.o
.PHONY : src/render/Render.cpp.o

src/render/Render.i: src/render/Render.cpp.i
.PHONY : src/render/Render.i

# target to preprocess a source file
src/render/Render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/Render.cpp.i
.PHONY : src/render/Render.cpp.i

src/render/Render.s: src/render/Render.cpp.s
.PHONY : src/render/Render.s

# target to generate assembly for a file
src/render/Render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/Render.cpp.s
.PHONY : src/render/Render.cpp.s

src/render/ResourceManager.o: src/render/ResourceManager.cpp.o
.PHONY : src/render/ResourceManager.o

# target to build an object file
src/render/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/ResourceManager.cpp.o
.PHONY : src/render/ResourceManager.cpp.o

src/render/ResourceManager.i: src/render/ResourceManager.cpp.i
.PHONY : src/render/ResourceManager.i

# target to preprocess a source file
src/render/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/ResourceManager.cpp.i
.PHONY : src/render/ResourceManager.cpp.i

src/render/ResourceManager.s: src/render/ResourceManager.cpp.s
.PHONY : src/render/ResourceManager.s

# target to generate assembly for a file
src/render/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/ResourceManager.cpp.s
.PHONY : src/render/ResourceManager.cpp.s

src/render/ShaderManager.o: src/render/ShaderManager.cpp.o
.PHONY : src/render/ShaderManager.o

# target to build an object file
src/render/ShaderManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/ShaderManager.cpp.o
.PHONY : src/render/ShaderManager.cpp.o

src/render/ShaderManager.i: src/render/ShaderManager.cpp.i
.PHONY : src/render/ShaderManager.i

# target to preprocess a source file
src/render/ShaderManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/ShaderManager.cpp.i
.PHONY : src/render/ShaderManager.cpp.i

src/render/ShaderManager.s: src/render/ShaderManager.cpp.s
.PHONY : src/render/ShaderManager.s

# target to generate assembly for a file
src/render/ShaderManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/src/render/ShaderManager.cpp.s
.PHONY : src/render/ShaderManager.cpp.s

vendor/imgui/backends/imgui_impl_glfw.o: vendor/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_glfw.o

# target to build an object file
vendor/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_glfw.cpp.o

vendor/imgui/backends/imgui_impl_glfw.i: vendor/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
vendor/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_glfw.cpp.i

vendor/imgui/backends/imgui_impl_glfw.s: vendor/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
vendor/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_glfw.cpp.s

vendor/imgui/backends/imgui_impl_wgpu.o: vendor/imgui/backends/imgui_impl_wgpu.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_wgpu.o

# target to build an object file
vendor/imgui/backends/imgui_impl_wgpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/backends/imgui_impl_wgpu.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_wgpu.cpp.o

vendor/imgui/backends/imgui_impl_wgpu.i: vendor/imgui/backends/imgui_impl_wgpu.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_wgpu.i

# target to preprocess a source file
vendor/imgui/backends/imgui_impl_wgpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/backends/imgui_impl_wgpu.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_wgpu.cpp.i

vendor/imgui/backends/imgui_impl_wgpu.s: vendor/imgui/backends/imgui_impl_wgpu.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_wgpu.s

# target to generate assembly for a file
vendor/imgui/backends/imgui_impl_wgpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/backends/imgui_impl_wgpu.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_wgpu.cpp.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_demo.o: vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.cpp.o

vendor/imgui/imgui_demo.i: vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.cpp.i

vendor/imgui/imgui_demo.s: vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_tables.o: vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.cpp.o

vendor/imgui/imgui_tables.i: vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.cpp.i

vendor/imgui/imgui_tables.s: vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyApp.dir/build.make CMakeFiles/MyApp.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... MyApp"
	@echo "... assimp"
	@echo "... spdlog"
	@echo "... unit"
	@echo "... zlibstatic"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Node.o"
	@echo "... src/Node.i"
	@echo "... src/Node.s"
	@echo "... src/core/Log.o"
	@echo "... src/core/Log.i"
	@echo "... src/core/Log.s"
	@echo "... src/core/Window.o"
	@echo "... src/core/Window.i"
	@echo "... src/core/Window.s"
	@echo "... src/io/cursor.o"
	@echo "... src/io/cursor.i"
	@echo "... src/io/cursor.s"
	@echo "... src/io/filesystem.o"
	@echo "... src/io/filesystem.i"
	@echo "... src/io/filesystem.s"
	@echo "... src/io/keyboard.o"
	@echo "... src/io/keyboard.i"
	@echo "... src/io/keyboard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/platform/osx/OSXWindow.o"
	@echo "... src/platform/osx/OSXWindow.i"
	@echo "... src/platform/osx/OSXWindow.s"
	@echo "... src/platform/web/WebWindow.o"
	@echo "... src/platform/web/WebWindow.i"
	@echo "... src/platform/web/WebWindow.s"
	@echo "... src/render/PipelineManager.o"
	@echo "... src/render/PipelineManager.i"
	@echo "... src/render/PipelineManager.s"
	@echo "... src/render/Render.o"
	@echo "... src/render/Render.i"
	@echo "... src/render/Render.s"
	@echo "... src/render/ResourceManager.o"
	@echo "... src/render/ResourceManager.i"
	@echo "... src/render/ResourceManager.s"
	@echo "... src/render/ShaderManager.o"
	@echo "... src/render/ShaderManager.i"
	@echo "... src/render/ShaderManager.s"
	@echo "... vendor/imgui/backends/imgui_impl_glfw.o"
	@echo "... vendor/imgui/backends/imgui_impl_glfw.i"
	@echo "... vendor/imgui/backends/imgui_impl_glfw.s"
	@echo "... vendor/imgui/backends/imgui_impl_wgpu.o"
	@echo "... vendor/imgui/backends/imgui_impl_wgpu.i"
	@echo "... vendor/imgui/backends/imgui_impl_wgpu.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

